exclude: docs/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=3000']
    -   id: check-ast
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: detect-aws-credentials
        args: [--allow-missing-credentials]
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: name-tests-test
        exclude: tests/extra/util.py
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
    -   id: mdformat
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length", "120"]
-   repo: https://github.com/jendrikseipp/vulture
    rev: v2.6
    hooks:
    - id: vulture
      name: vulture
      language: python
      entry: vulture
      description: Find unused Python code.
      types: [python]
      pass_filenames: false
      require_serial: true
      args: ["--min-confidence", "90", "Home.py"]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
